### ISSUE TITLE
the noise_filenum

### ISSUE THREAD

**Issue by guozhonghao1994** [JanhHyun/Speaker_Verification#1]
Hi! I have a question on your noise extraction part.
In configuration.py you've marked the "noise_filenum" as "how many noise files will you use". In data_preprocess you seem to extract noises from each paired noise-clean data and save them as a *.npy file. In TD-SV train&test, however, you set the "noise_filenum" to default(16), which means that you add just #16 noise to any utterance. 
So what does "how many noise files will you use" mean? I think it's better to say "the # of noise file you will use". Is my understanding correct?

**Comment by guozhonghao1994** [comment]
By the way, I can't see where your cossim() is used...do you have any idea about that?

**Comment by Janghyun1230** [comment]
Sorry for late reply. For the first question you're right. Because I could not get public dataset for td-sv (several samples per person with same content) , so I tried to generate them by adding various noise. So "how many noise files will you use" means how many noise type will be used for such  dataset.

**Comment by Janghyun1230** [comment]
And at the first time, I used cossim() function... however, I think after modification it's not used anymore..
